FROM apache/airflow:2.10.4-python3.11

USER root
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*
USER airflow

RUN pip install --no-cache-dir pandas scikit-learn scipy implicit numpy
